apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-recommend-server
  namespace: ai-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-recommend-server
  template:
    metadata:
      labels:
        app: food-recommend-server
    spec:
      containers:
      - name: food-recommend-server
        image: yunseocloud/food-recommend-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "192.168.1.8"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "GoormBbang"
        - name: DB_USER
          value: "cloudbread"
        - name: DB_PASSWORD
          value: "1234"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: food-recommend-server-svc
  namespace: ai-services
spec:
  selector:
    app: food-recommend-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

