# ocr-backend-deployment.yaml
# OCR 서버의 Deployment와 Service를 하나의 파일로 정의

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-server-deployment
  namespace: backend # backend 네임스페이스에 배포
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-server
  template:
    metadata:
      labels:
        app: ocr-server
    spec:
      containers:
      - name: ocr-server-container
        image: yunseocloud/ocr-server:latest
        envFrom:
            - secretRef:     # ConfigMap을 썼다면 secretRef 대신 configMapRef
                name: ocr-server-env
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-server-service
  namespace: backend # backend 네임스페이스에 배포
spec:
  selector:
    app: ocr-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP # 클러스터 내부에서만 접근 가능하도록 설정