apiVersion: v1
kind: Service
metadata:
  name: demo-frontend-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: demo-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
