# streamlit-frontend-deployment.yaml
# 프론트엔드 Deployment와 Service 정의

apiVersion: apps/latest
kind: Deployment
metadata:
  name: demo-frontend-deployment
  namespace: frontend # <--- frontend 네임스페이스에 배포
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: demo-frontend-container
        image: yunseocloud/demo-frontend:latest
        ports:
        - containerPort: 8501
---
apiVersion: latest
kind: Service
metadata:
  name: demo-frontend-service
  namespace: frontend # <--- frontend 네임스페이스에 배포
spec:
  selector:
    app: demo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer # <--- 외부에서 접근할 수 있도록 로드 밸런서 타입 사용