# 배포 대상 네임스페이스는 설치 시 --namespace로 지정하는 것을 권장합니다.
# 필요하면 여기서 기본값을 참고만 하세요.
namespace: backend

replicaCount: 2

image:
  repository: yunseocloud/chatbot-server
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30667

# 필요 시 리소스 제한을 켜세요.
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Health check 설정
healthCheck:
  readinessProbe:
    path: /health
    port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
  livenessProbe:
    path: /health
    port: 8000
    initialDelaySeconds: 30
    periodSeconds: 20

# 추가 환경변수가 필요하면 여기에
env: []
envFrom:
  - secretRef:
      name: chatbot-server-env