apiVersion: apps/latest
kind: Deployment
metadata:
  name: {{ include "ocr-server.fullname" . }}
  labels:
    {{- include "ocr-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ocr-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ocr-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ocr-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
