apiVersion: v1
kind: Service
metadata:
  name: chatbot-server-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chatbot-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chatbot-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}